---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  type: LoadBalancer  # This will automatically assign an external IP
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 80
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2