apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:                    
    app: apache      
spec:
  containers:
  - image: httpd:latest
    name: apache
    ports:
    - containerPort: 80 
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs    # Mount the volume at the default Apache web root path
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # Directory location on host containing the index.html file
      path: /tmp
      # This field is optional
      type: Directory
