apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: YWRtaW4=  # Base64-encoded value of "admin"
  password: YWRtaW4xMjM=  # Base64-encoded value of "admin123"

