apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8501
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2